insert into khoadieutri
values

('1', 'dị ứng học'),
('2', 'chuyên khoa gây mê'),
('3', 'nam khoa'),
('4', 'khoa tim'),
('5', 'chuyên khoa da liễu'),
('6', 'khoa dinh dưỡng'),
('7', 'khoa nội tiết'),
('8', 'khoa dịch tễ học'),
('9', 'khoa tiêu hóa'),
('10', 'lão khoa. đn. gerontology'),
('11', 'phụ khoa'),
('12', 'khoa huyết học'),
('13', 'miễn dịch học'),
('14', 'khoa bệnh nhân ngoại trú'),
('15', 'nội khoa'),
('16', 'thận học'),
('17', 'khoa thần kinh'),
('18', 'ngoại thần kinh'),
('19', 'y học hạt nhân'),
('20', 'khoa răng'),
('21', 'ung thư học'),
('22', 'khoa mắt'),
('23', 'khoa chỉnh hình'),
('24', 'ngoại chỉnh hình. đn. orthopedics'),
('25', 'khoa bệnh nhân ngoại trú'),
('26', 'phẫu thuật tạo hình'),
('27', 'y học dự phòng'),
('28', 'ngoại khoa'),
('29', 'ngoại lồng ngực'),
('30', 'khoa chấn thương'),
('31', 'niệu khoa');